name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 17
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider yarn install
          export NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
